enum MAIN_STACK_NAVIGATOR {
  HOME_TAB_NAVIGATOR = 'HOME_TAB_NAVIGATOR',
}

enum AUTH_STACK_NAVIGATOR {
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  HOME = 'HOME',
  HOME_DETAILS = 'HOME_DETAILS',
  ACCOUNT = 'ACCOUNT',
  MEDICATION_LIST = 'MEDICATION_LIST',
  MEDICATION_DETAIL = 'MEDICATION_DETAIL',
  ADD_MEDICATION = 'ADD_MEDICATION',
}

enum HOME_TAB_NAVIGATOR {
  HOME = 'HOME',
  HOME_DETAILS = 'HOME_DETAILS',
  CARE_PLAN = 'CARE_PLAN',
  MEDICATION = 'MEDICATION',
  DEVICES = 'DEVICES',
}

enum MEDICATION_STACK_NAVIGATOR {
  MEDICATION_LIST = 'MEDICATION_LIST',
  MEDICATION_DETAIL = 'MEDICATION_DETAIL',
  ADD_MEDICATION = 'ADD_MEDICATION',
}

export { MAIN_STACK_NAVIGATOR, AUTH_STACK_NAVIGATOR, HOME_TAB_NAVIGATOR, MEDICATION_STACK_NAVIGATOR };
